# Generated by Django 5.0.3 on 2024-04-22 13:11

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=20,
                null=True,
                region=None,
                verbose_name="Телефон",
            ),
        ),
    ]
