# Generated by Django 5.0.3 on 2024-04-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="verification_code",
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Код верификации"
            ),
        ),
    ]
