# Generated by Django 5.0.3 on 2024-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="slug"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
