# Generated by Django 5.0.3 on 2024-03-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blog_is_published_blog_slug_blog_views"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="views",
            new_name="views_count",
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="slug"
            ),
        ),
    ]
